import "./globals.css";
import localFont from "next/font/local";


export const metadata = {
    title: "TSK",
    description: "Generated by create next app",
};

const inter = localFont({src: './fonts/Inter.ttf', variable: '--font-inter'});
const montserrat = localFont({src: './fonts/Montserrat.ttf', variable: '--font-montserrat'});

export default function RootLayout({children}) {
    return (
        <html lang="ru">
        <body
            className={`${montserrat.variable} ${inter.variable}`}>
        {children}
        </body>
        </html>
    );
}
